//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file was automatically generated by RisohEditor.
// YappyCam_res.rc

#define IDC_STATIC                          -1

#define IDB_REC                             100
#define IDB_STOP                            101
#define IDB_PAUSE                           102
#define IDB_DOTS                            103

#define IDD_MAIN                            100
#define IDD_SOUNDINPUT                      101
#define IDD_SCREEN                          102
#define IDD_WEBCAMERA                       103
#define IDD_PICINPUT                        104
#define IDD_SETBYDRAG                       105

#define IDR_SILENT_WAV                      1
#define IDR_MAINMENU                        1000

#define IDS_FORMAT                          100
#define IDS_BLACK                           101
#define IDS_WHITE                           102
#define IDS_SCREEN                          103
#define IDS_WEBCAMERA                       104
#define IDS_MONITOR                         105
#define IDS_CAMERA                          106
#define IDS_PRIMARYMONITOR                  107
#define IDS_VIRTUALSCREEN                   108

#define ID_PICTUREINPUT                     100
#define ID_SOUNDINPUT                       101
#define ID_ABOUT                            102
#define ID_CONFIGCLOSED                     103

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    1001
        #define _APS_NEXT_COMMAND_VALUE     104
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
