//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file was automatically generated by RisohEditor.
// YappyCam_res.rc

#define IDC_STATIC                          -1

#define IDB_REC                             100
#define IDB_STOP                            101
#define IDB_PAUSE                           102
#define IDB_DOTS                            103

#define IDD_MAIN                            100
#define IDD_SOUNDINPUT                      101

#define IDR_SILENT_WAV                      1
#define IDR_MAINMENU                        1000

#define IDS_FORMAT                          100

#define ID_PICTUREINPUT                     100
#define ID_SOUNDINPUT                       101
#define ID_ABOUT                            102

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    1001
        #define _APS_NEXT_COMMAND_VALUE     103
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
