//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file was automatically generated by RisohEditor.
// YappyCam_res.rc

#define IDC_STATIC                          -1

#define IDB_REC                             100
#define IDB_STOP                            101
#define IDB_PAUSE                           102
#define IDB_DOTS                            103

#define IDD_MAIN                            100
#define IDD_SOUNDINPUT                      101
#define IDD_SCREEN                          102
#define IDD_WEBCAMERA                       103
#define IDD_PICINPUT                        104
#define IDD_SETBYDRAG                       105
#define IDD_SAVETO                          106
#define IDD_HOTKEYS                         107
#define IDD_MULTIRESO                       108
#define IDD_IMAGEFILE                       109
#define IDD_PLUGINS                         110

#define IDI_MAIN                            100

#define IDR_SILENT_WAV                      1
#define IDR_STARTREC                        2
#define IDR_ENDREC                          3
#define IDR_DOWN                            4
#define IDR_SHUTTER                         5
#define IDR_MAINMENU                        1000

#define IDS_FORMAT                          100
#define IDS_BLACK                           101
#define IDS_WHITE                           102
#define IDS_SCREEN                          103
#define IDS_WEBCAMERA                       104
#define IDS_MONITOR                         105
#define IDS_CAMERA                          106
#define IDS_PRIMARYMONITOR                  107
#define IDS_VIRTUALSCREEN                   108
#define IDS_APPTITLE                        109
#define IDS_DRAGONME                        110
#define IDS_FINALIZEFAIL                    111
#define IDS_FINALIZED                       112
#define IDS_FINALIZING                      113
#define IDS_WANNAFINALIZE                   114
#define IDS_FINALIZEQUE                     115
#define IDS_FINALIZEPERCENTS                116
#define IDS_FINALIZEDONE                    117
#define IDS_FINALIZECANCELLED               118
#define IDS_SETLOCATION                     119
#define IDS_VERSIONTEXT                     120
#define IDS_VERSIONCAPTION                  121
#define IDS_QUERYINIT                       122
#define IDS_SCANNING                        123
#define IDS_FRAMEDROP                       124
#define IDS_FINALIZECANC2                   125
#define IDS_IMAGEFILE                       126
#define IDS_NAME                            127
#define IDS_FILENAME                        128
#define IDS_PASS                            129
#define IDS_PASS1                           130
#define IDS_PASS2                           131
#define IDS_PASS1AND2                       132
#define IDS_PICINPUT                        133
#define IDS_FUSEBOX                         134
#define IDS_SOUNDBOX                        135
#define IDS_BROADCASTER                     136
#define IDS_UNKNOWN                         137
#define IDS_TYPE                            138

#define ID_PICTUREINPUT                     100
#define ID_SOUNDINPUT                       101
#define ID_ABOUT                            102
#define ID_CONFIGCLOSED                     103
#define ID_FINALIZED                        104
#define ID_FINALIZEFAIL                     105
#define ID_FINALIZECANCEL                   106
#define ID_SAVETO                           107
#define ID_EXIT                             108
#define ID_HOTKEYS                          109
#define ID_INITSETTINGS                     110
#define ID_OPENFOLDER                       111
#define ID_FINALIZECANCEL2                  112
#define ID_TAKEASHOT                        113
#define ID_PLUGINS                          114

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    1001
        #define _APS_NEXT_COMMAND_VALUE     115
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
