//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file was automatically generated by RisohEditor.
// Clock_yap_res.rc

#define IDC_STATIC                          -1

#define IDD_CONFIG                          100

#define IDS_TITLE                           100
#define IDS_LEFT                            101
#define IDS_CENTER                          102
#define IDS_RIGHT                           103
#define IDS_TOP                             104
#define IDS_MIDDLE                          105
#define IDS_BOTTOM                          106

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
